language: csharp
solution: conekta-csharpnet.sln
install:
  - nuget restore conekta-csharpnet.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release conekta-csharpnet.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ConektaCSharp.Tests/bin/Release/ConektaCSharp.Tests.dll